---
- hosts: final
  become: true
  gather_facts: no

#  pre_tasks:
#    - raw: yum install -y python3 python3-pip

  tasks:
    - name: Install snapd
      yum: name=snapd state=latest enabled=yes
      shell: sudo systemctl enable --now snapd.socket
      shell: sudo ln -s /var/lib/snapd/snap /snap
      shell: sudo systemctl start snapd

    - name: Remove certbot-auto and any Certbot OS packages
      yum: name=certbot state=absent

    - name: Install Certbot
      shell: sudo snap install --classic certbot
      shell: sudo ln -s /snap/bin/certbot /usr/bin/certbot

    - name: Create directory /var/www
      ansible.builtin.file:
        path: /var/www
        state: directory
	owner: nginx
	group: nginx
        mode: '0755'

    - name: Create directory /var/www/html
      ansible.builtin.file:
        path: /var/www/html
        state: directory
	owner: nginx
	group: nginx
        mode: '0755'

    - name: Create directory /var/www/html/{{ domain_name }}
      ansible.builtin.file:
        path: /var/www/html/{{ domain_name }}
        state: directory
	owner: nginx
	group: nginx
        mode: '0755'

    - name: Install nginx
      yum: name=nginx state=latest enabled=yes

    - name: Install system nginx config
      template:
        src: templates/sneo.conf
        dest: /etc/nginx/nginx.conf

    - name: Start nginx service
      service: name=nginx state=started

      shell: sudo certbot --nginx

    - name: Create letsencrypt certificate
      shell: sudo certbot certonly --webroot -w /var/www/html --non-interactive --agree-tos -m {{ letsencrypt_email }} -d {{ domain_name }}

    - name: Install system nginx Final config
      template:
        src: templates/sneo.conf.final
        dest: /etc/nginx/nginx.conf

    - name: Start nginx service
      service: name=nginx state=restarted
